export default {
  name: 'Nomie 6 dev',
  short_name: 'Nomie 6',
  start_url: '/',
  description: 'Private Life Tracking',
  orientation: 'portrait',
  display: 'standalone',
  theme_color: '#000000',
  background_color: '#000000',
  prompt_message: 'Add a Home screen icon for easy access to Nomie',
  lang: 'en-us',
  id: '/',

  screenshots: [
    {
      src: 'screenshots/track-screenshot.png',
      sizes: '375x666',
      type: 'image/png',
      platform: 'narrow',
      label: 'Tracking Board',
    },
    {
      src: 'screenshots/popmenu-screenshot.png',
      sizes: '375x666',
      type: 'image/png',
      platform: 'narrow',
      label: 'Tracker Options',
    },
    {
      src: 'screenshots/stats-screenshot.png',
      sizes: '375x666',
      type: 'image/png',
      platform: 'narrow',
      label: 'Tracker Stats',
    },
  ],
  icons: [
    {
      src: '/app-icons/nomie6-head-72.png',
      sizes: '72x72',
      type: 'image/png',
      purpose: 'any',
    },
    {
      src: '/app-icons/nomie6-head-96.png',
      sizes: '96x96',
      type: 'image/png',
      purpose: 'any',
    },
    {
      src: '/app-icons/nomie6-head-120.png',
      sizes: '120x120',
      type: 'image/png',
      purpose: 'any',
    },
    {
      src: '/app-icons/nomie6-head-128.png',
      sizes: '128x128',
      type: 'image/png',
      purpose: 'any',
    },
    {
      src: '/app-icons/nomie6-head-144.png',
      sizes: '144x144',
      type: 'image/png',
      purpose: 'any',
    },
    {
      src: '/app-icons/nomie6-head-152.png',
      sizes: '152x152',
      type: 'image/png',
      purpose: 'any',
    },
    {
      src: '/app-icons/nomie6-head-180.png',
      sizes: '180x180',
      type: 'image/png',
      purpose: 'any',
    },
    {
      src: '/app-icons/nomie6-head-192.png',
      sizes: '192x192',
      type: 'image/png',
      purpose: 'any',
    },
    {
      src: '/app-icons/nomie6-head-384.png',
      sizes: '384x384',
      type: 'image/png',
      purpose: 'any',
    },
    {
      src: '/app-icons/nomie6-head-192.png',
      sizes: '192x192',
      type: 'image/png',
      purpose: 'maskable',
    },
    {
      src: '/app-icons/nomie6-head-384.png',
      sizes: '384x384',
      type: 'image/png',
      purpose: 'maskable',
    },
    {
      src: '/app-icons/nomie6-head-512.png',
      sizes: '512x512',
      type: 'image/png',
      purpose: 'any',
    },
    {
      src: '/app-icons/nomie6-head-512.png',
      sizes: '512x512',
      type: 'image/png',
      purpose: 'maskable',
    },
  ],
}
